# Minimal Railway service config
[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"     # or ALWAYS
healthcheckPath = "/"                # our app has GET "/"
healthcheckTimeout = 300

[service]
name = "stripe-fulfillment"
